<a href="https://colab.research.google.com/github/adilcmj/forge-kamala/blob/main/Copy_of_IICT_fake_news.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df = pd.read_csv("fakenews_mastersheet.csv")

In [ ]:
print(df.head())
print(df.columns)
print(df.shape)
print(df.info())

                                  title  \
0               Foreign Democrat final.
1   To offer down resource great point.
2          Himself church myself carry.
3                  You unit its should.
4  Billion believe employee summer how.

                                                text        date    source  \
0  more tax development both store agreement lawy...  10-03-2023  NY Times
1  probably guess western behind likely next inve...  25-05-2022  Fox News
2  them identify forward present success risk sev...  01-09-2022       CNN
3  phone which item yard Republican safe where po...  07-02-2023   Reuters
4  wonder myself fact difficult course forget exa...  03-04-2023       CNN

                 author    category  label
0          Paula George    Politics      0
1           Joseph Hill    Politics      1
2        Julia Robinson    Business      1
3  Mr. David Foster DDS     Science      1
4         Austin Walker  Technology      1
Index(['title', 'text', 'date', 'source', 'author', 'category', 'label'], dtype='object')
(20000, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     20000 non-null  object
 1   text      20000 non-null  object
 2   date      20000 non-null  object
 3   source    19000 non-null  object
 4   author    19000 non-null  object
 5   category  20000 non-null  object
 6   label     20000 non-null  int64
dtypes: int64(1), object(6)
memory usage: 1.1+ MB
None

In [ ]:
df.isnull().sum()

title          0
text           0
date           0
source      1000
author      1000
category       0
label          0
dtype: int64

In [ ]:
df["label"].value_counts()

label
1    10056
0     9944
Name: count, dtype: int64

In [ ]:
df.duplicated(subset=["title","text"]).sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates(subset=["title", "text"])

In [ ]:
df["title"] = df["title"].fillna("")
df["text"] = df["text"].fillna("")

In [ ]:
df["content"] = df["title"] + " " + df["text"]

X = df["content"]
y = df["label"]

In [ ]:
df["clean_content"] = df["content"]

In [ ]:
print(df.columns.tolist())

['title', 'text', 'date', 'source', 'author', 'category', 'label', 'content', 'clean_content']

In [ ]:
df["clean_content"] = df["clean_content"].str.lower()

In [ ]:
df["clean_content"] = df["clean_content"].str.replace(r"http\S+|www\S+", "", regex=True)

In [ ]:
df["clean_content"] = df["clean_content"].str.replace(r"<.*?>", "", regex=True)

In [ ]:
df["clean_content"] = df["clean_content"].str.replace(r"[^\w\s]", "", regex=True)

In [ ]:
df["clean_content"] = df["clean_content"].str.replace(r"\s+", " ", regex=True).str.strip()

In [ ]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

df["clean_content"] = df["clean_content"].apply(
    lambda text: " ".join(
        word for word in text.split() if word not in stop_words
    )
)

In [ ]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize

df["tokens"] = df["clean_content"].apply(word_tokenize)

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

In [ ]:
from google.colab import files

files.download("cleaned_dataset.csv")